config/routes.rb
Rails.application.routes.draw do

  resources :products, only: [:index, :show, :destroy]
  root 'products#index'

end

app/models/product.rb
class Product < ActiveRecord::Base
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/products_controller.rb
class ProductsController < ApplicationController

    def index
      @products = Product.all
    end

    def show
      @product = Product.find(params[:id])
    end

    def destroy
      Product.destroy(params[:id])
      redirect_to action: "index"
    end

end

# redirect_to "/products"

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Shopping Cart</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= stylesheet_link_tag '../assets/stylesheets/normalize.css' %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <link href='http://fonts.googleapis.com/css?family=Lato' rel='stylesheet' type='text/css'>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>

app/views/products/index.html.erb
<html>
  <head>
  <div id="header"><h1>Shopping Cart</h1></div>

<body>
 <div class="container">
        <div class="row" id="top">
          <div class="quarter">
            <div id="login_form">
             <form name="f1" method="post" action="login.php" id="f1">
            <table>
            <tr>
                <td class="f1_label"> user name :</td><td><input type="text" name="username" value="" />
                </td>
            </tr>
            <tr>
                <td class="f1_label">password :</td><td><input type="password" name="password" value="" />
                </td>
            </tr>
            <tr>
                <td>
                    <input type="submit" name="login" value="Log In"/>
                </td>
            </tr>
            </table>
          </form>
        </div>
      </div>
</div>
<body>
    <div class="container">
        <div class="row" id="bottom">
        <% @products.each do |product| %>
          <li>
            <img src= <%= product.image_url %>>
            <strong><%= product.name %></strong>
            <%= simple_format(product.description) %>
            <em><%= product.price %></em>
            <br />
            <%= link_to "Details", product_path(product) %>
          </li>
        <% end %>
      </ul>
    </div>

  <footer><div id='footer'>www.shoppingcart.com</div></footer>

</body>

</html>

app/views/products/show.html.erb
<h1><%= @product.name %></h1>
<%= simple_format(@product.description) %>
<em><%= @product.price %></em>
<br />
<%= link_to "Product List", products_path %>
<%= link_to "Delete", @product, method: :delete %>